//------------------------------------------------------------------------
// Copyright(c) 2023 Bill50han.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"White Noise Generator.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"White Noise Generator VST3 (64Bit)"
#else
#define stringFileDescription	"White Noise Generator VST3"
#endif
#define stringCompanyName		"Bill50han\0"
#define stringLegalCopyright	"Copyright(c) 2023 Bill50han."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
